stages:
  - build
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  # image: docker:28.1.1
  # services:
  #   - docker:28.1.1-dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cp "$ENV_FILE" .env
  script:
    - docker compose up -d
  artifacts:
    paths:
      - .  
# deploy:
#   stage: deploy
#   script:
#     - docker-compose logs