stages:
  - build
  - test
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  before_script:
    - cp "$ENV_FILE" .env
  script:
    - docker compose up -d # Ensures fresh start
  artifacts:
    paths:
      - ./metrics/prometheus.yml  # Makes it available for later jobs

test:
  stage: test
  before_script:
    - apk update && apk add make
  script:
    - make test

# deploy:
#   stage: deploy
#   script:
#     - docker-compose logs