stages:
  - build
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  # image: docker:28.1.1
  # services:
  #   - docker:28.1.1-dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker-compose -f docker-compose.yml up -d --build
    - docker-compose ps

deploy:
  stage: deploy
  script:
    - docker-compose logs