stages:
  - test
  - build
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app


test:
  stage: test
  image: golang:1.24
  services:
    - name: postgres:15
      alias: postgres
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: test
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h postgres -U $POSTGRES_USER; do sleep 1; done
  script:
    - go mod download
    - make test

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  before_script:
    - cp "$ENV_FILE" .env
  script:
    - docker compose up -d # Ensures fresh start
  # artifacts:
  #   paths:
  #     - ./metrics/prometheus.yml  # Makes it available for later jobs


# deploy:
#   stage: deploy
#   script:
#     - docker-compose logs