stages:
  - build
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  # image: docker:28.1.1
  # services:
  #   - docker:28.1.1-dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cp "$ENV_FILE" .env
    - mkdir -p ./metrics  # Create metrics directory if it doesn't exist
    # - if [ ! -f ./metrics/prometheus.yml ]; then touch ./metrics/prometheus.yml; fi  # Create empty file if it doesn't exist
    - chmod 644 ./metrics/prometheus.yml
  script:
    - docker compose up -d

# deploy:
#   stage: deploy
#   script:
#     - docker-compose logs