stages:
  - build
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  before_script:
    - cp "$ENV_FILE" .env
    - mkdir -p ./metrics  # Create metrics directory if it doesn't exist
  script:
    - docker compose up -d --force-recreate  # Ensures fresh start
  artifacts:
    paths:
      - ./metrics/prometheus.yml  # Makes it available for later jobs
# deploy:
#   stage: deploy
#   script:
#     - docker-compose logs