stages:
  - test
  - build
  - deploy

variables:
  COMPOSE_PROJECT_NAME: fiber_app


test-with-postgres:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpass
    POSTGRES_DB: testdb
  before_script:
    - apk add make
    - apk add --no-cache docker-cli bash curl
    - docker pull postgres:15
    - |
      docker run -d \
        --name test-postgres \
        -e POSTGRES_USER=$POSTGRES_USER \
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
        -e POSTGRES_DB=$POSTGRES_DB \
        -p 5432:5432 \
        postgres:15
    - |
      echo "⏳ Waiting for PostgreSQL to be ready..."
      until docker exec test-postgres pg_isready -U $POSTGRES_USER; do sleep 1; done
  script:
    - echo "✅ PostgreSQL is up. Running tests..."
    - make test
  after_script:
    - echo "🧹 Cleaning up..."
    - docker stop test-postgres
    - docker rm test-postgres

before_script:
  - echo "Running CI pipeline..."
  - docker info

build:
  stage: build
  before_script:
    - cp "$ENV_FILE" .env
  script:
    - docker compose up -d # Ensures fresh start
  # artifacts:
  #   paths:
  #     - ./metrics/prometheus.yml  # Makes it available for later jobs


# deploy:
#   stage: deploy
#   script:
#     - docker-compose logs