version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - go_network  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  go_network:
    driver: bridge