global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'fiber-app'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 15s
    scrape_timeout: 10s
    follow_redirects: true
    static_configs:
      - targets: ['192.168.2.58:3000']